services:
  - type: web
    name: movie-booking-ticket
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/jav_projecto1-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
